[package]
name = "ferros"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>", "Zack Pierce <zack@auxon.io"]
edition = "2018"

[features]
default = ["four_param_rights"]
test_support = []
four_param_rights = []

[dependencies]
# NOTE: We use a git dependency directly since the git submodules
# don't currently work when pulled down from crates.io
selfe-sys = { git = "ssh://git@github.com/auxoncorp/selfe-sys.git" }
typenum = { git = "ssh://github.com/auxoncorp/typenum" }
registers = { git = "ssh://github.com/auxoncorp/registers" }
generic-array = { git = "ssh://github.com/auxoncorp/generic-array", branch = "auxon-typenum" }
cross_queue = { path = "./cross_queue" }
smart_alloc = { path = "./smart_alloc" }

[dependencies.arrayvec]
version = "0.4.10"
default-features = false

[build-dependencies]
selfe-config = { git = "ssh://git@github.com/auxoncorp/selfe-sys.git" }
