[package]
name = "ferros"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>", "Zack Pierce <zack@auxon.io"]
edition = "2018"

[dependencies]
# NOTE: We use a git dependency directly since the git submodules
# don't currently work when pulled down from crates.io
libsel4-sys-gen = { path = "/home/mullr/devel/confignoble/libsel4-sys-gen" } # { git = "ssh://git@github.com/auxoncorp/confignoble.git", branch = "master" }
typenum = { git = "ssh://github.com/auxoncorp/typenum" }
registers = { git = "ssh://github.com/auxoncorp/registers" }
generic-array = { git = "ssh://github.com/auxoncorp/generic-array", branch = "auxon-typenum" }
cross_queue = { path = "./cross_queue" }
smart_alloc = { path = "./smart_alloc" }

[dependencies.arrayvec]
version = "0.4.10"
default-features = false

[dependencies.wee_alloc]
version = "0.4"
features = ["static_array_backend"]
optional = true

[dependencies.proptest]
version = "0.8.6"
default-features = false
features = ["alloc", "nightly"]
optional = true

[build-dependencies]
fel4-config = { git = "ssh://github.com/auxoncorp/fel4-config" }

[features]
default = []
alloc = ["wee_alloc"]
test = ["alloc", "proptest"]
