[package]
name = "ferros"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>", "Zack Pierce <zack@auxon.io"]
edition = "2018"

[features]
default = []
test_support = []

[dependencies]
selfe-sys = { git = "ssh://git@github.com/auxoncorp/selfe-sys.git" }
typenum = { git = "ssh://github.com/auxoncorp/typenum" }
registers = { git = "ssh://github.com/auxoncorp/registers" }
generic-array = { git = "ssh://github.com/auxoncorp/generic-array", branch = "auxon-typenum" }
cross_queue = { path = "./cross_queue" }
smart_alloc = { path = "./smart_alloc" }
pdqsort = "1"
heapless = "0.4.4"

[dependencies.arrayvec]
version = "0.4.10"
default-features = false

[patch.crates-io]
typenum = { git = "ssh://github.com/auxoncorp/typenum" }
hash32 = { git = "ssh://github.com/auxoncorp/hash32", branch = "no-std" }
generic-array = { git = "ssh://github.com/auxoncorp/generic-array", branch = "auxon-typenum" }

[build-dependencies]
selfe-config = { git = "ssh://git@github.com/auxoncorp/selfe-sys.git" }
