### TX1 (ARMv8)
[build.tx1]
cross_compiler_prefix = "aarch64-linux-gnu-"

[build.tx1.debug]
make_root_task = "cargo xbuild --target=aarch64-unknown-linux-gnu"
root_task_image = "target/aarch64-unknown-linux-gnu/debug/vmm"

[build.tx1.release]
make_root_task = "cargo xbuild --target=aarch64-unknown-linux-gnu --release"
root_task_image = "target/aarch64-unknown-linux-gnu/release/vmm"

[sel4]
# We need some of the changes since last release for TX1/aarch64 hyp support
# These refs are from master as of 10MAY2019
kernel = { git = "https://github.com/seL4/seL4" , rev = "4d0f02c029560cae0e8d93727eb17d58bcecc2ac" }
tools = { git = "https://github.com/seL4/seL4_tools" , rev = "f3b4bef672b92858c139787bc6fd5124e6022d26" }
util_libs  = { git = "https://github.com/seL4/util_libs" , rev = "98aaebe56c66d46576485216f8c4626ed76a3757" }

### arch

[sel4.config.arm]
KernelArch = 'arm'
KernelIPCBufferLocation = 'threadID_register'

### sel4_arch

[sel4.config.aarch64]
KernelSel4Arch = 'aarch64'
KernelArmSel4Arch = 'aarch64'

### platform

[sel4.config.tx1]
KernelARMPlatform = 'tx1'
KernelHaveFPU = true
ElfloaderImage = 'binary'
KernelArmHypervisorSupport = true

### Build mode

[sel4.config.debug]
KernelPrinting = true
KernelDebugBuild = true

[sel4.config.release]
KernelPrinting = false
KernelDebugBuild = false
KernelOptimisation = '-O2'

[sel4.config]
KernelColourPrinting = true
KernelUserStackTraceLength = 16
KernelVerificationBuild = false
KernelBenchmarks = 'none'
KernelFastpath = true
LibSel4FunctionAttributes = 'public'
KernelNumDomains = 1
HardwareDebugAPI = false
KernelFWholeProgram = false
KernelResetChunkBits = 8
KernelNumPriorities = 256
KernelStackBits = 12
KernelTimeSlice = 5
KernelTimerTickMS = 2
KernelMaxNumNodes = 1
KernelRetypeFanOutLimit = 16384
KernelRootCNodeSizeBits = 19
KernelMaxNumBootinfoUntypedCaps = 230
KernelSupportPCID = false
KernelDebugDisablePrefetchers = false
KernelExportPMCUser = false
KernelFPU = 'FXSAVE'
KernelFPUMaxRestoresSinceSwitch = 64
KernelFSGSBase = 'msr'
KernelHugePage = true
KernelIOMMU = false
KernelIRQController = 'IOAPIC'
KernelIRQReporting = true
KernelLAPICMode = 'XAPIC'
KernelMaxNumIOAPIC = 1
KernelMaxNumWorkUnitsPerPreemption = 100
KernelMultiboot1Header = true
KernelMultiboot2Header = true
KernelMultibootGFXMode = 'none'
KernelSkimWindow = true
KernelSyscall = 'syscall'
KernelXSaveSize = 576
LinkPageSize = 4096
