[package]
name = "mock"
version = "0.1.0"
authors = ["Zachary Pierce <zack@auxon.io>"]
edition = "2018"

[dependencies]
ferros-test = { path = "../.." , default-features = false }
typenum = "1.10"
ferros = { path = "mock-ferros" }
