[package]
name = "mock"
version = "0.1.0"
authors = ["Zachary Pierce <zack@auxon.io>"]
edition = "2018"

[dependencies]
ferros-test = { path = "../.." , default-features = false }
typenum = { git = "ssh://github.com/auxoncorp/typenum.git" }
ferros = { path = "mock-ferros" }
