[package]
name = "build-script"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferros-build = { path="../../../../ferros-build" }