[package]
name = "ferros-build"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

[dependencies]
selfe-arc = { git = "ssh://git@github.com/auxoncorp/selfe-sys.git" }
xmas-elf = "0.7"
memmap = "0.7"