[package]
name = "ferros-build"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"
resolver = "2"

[dependencies]
selfe-arc = { git = "https://github.com/auxoncorp/selfe-sys" }
xmas-elf = "0.7"
memmap = "0.7"
